profiles="rdistro-minimal"
auto_profiles="rdistro-minimal"

locale="en_US.UTF-8"

debian_mirror="http://snapshot.debian.org/archive/debian/20260813T165000Z/"
security_mirror=""
updates_mirror=""

mirror_components="main"

export ARCH=arm64

custom_installer="/custom-installer"
ignore_missing_checksums="true"

mirror_files=""
export OMIT_DOC_TOOLS=1

export OMIT_MANUAL=1
export OMIT_RELEASE_NOTES=1
export DOJIGDO=0
export MAXCDS=1
export INSTALLER_CD=2

export DISKINFO="R-Distro 0.1 Minimal ARM64 Installer"